name: 'anime_engine'
version: 0.0.1
description: Animation framework

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  stagexl: "^0.13.0"
  vector_math:
  core_engine:
        git:
            url: https://github.com/jox81/core_engine.git

dev_dependencies:
  test:

dependency_overrides:
  core_engine:
    path: ../core_engine